/**
 * Shared helpers for SeeYa's client auth.
 *
 * SeeYa uses Supabase email+password auth, but most of our clients
 * don't have/use email — they're WhatsApp-native. So we treat the
 * phone number as the primary identity:
 *
 * - If the admin provides a real email, we use it for auth.
 * - Otherwise, we construct a synthetic email `<phone-digits>@seeya.app`
 *   so Supabase has something to store; the client never sees it.
 *
 * Login accepts either form. If the user types digits, we map to
 * the synthetic email; if she types something with `@`, we use it
 * as-is.
 */

/** Domain we use to fabricate "internal" emails from phone numbers. */
export const SEEYA_INTERNAL_DOMAIN = "seeya.app";

/** Strip everything that isn't a digit. */
export function normalizePhone(phone: string): string {
  return phone.replace(/\D/g, "");
}

/**
 * Build the email Supabase will store on auth.users.
 *
 * @param rawEmail   What the admin typed (may be empty).
 * @param phone      The client's phone (required — used as fallback).
 * @returns The login email Supabase should use, or null when input is
 *          insufficient.
 */
export function resolveAuthEmail(
  rawEmail: string | null | undefined,
  phone: string,
): string | null {
  const email = (rawEmail ?? "").trim().toLowerCase();
  if (email) return email;

  const digits = normalizePhone(phone);
  if (digits.length < 7) return null;
  return `${digits}@${SEEYA_INTERNAL_DOMAIN}`;
}

/** True if the email was auto-generated by us (not a real address). */
export function isInternalEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  return email.toLowerCase().endsWith(`@${SEEYA_INTERNAL_DOMAIN}`);
}

/**
 * Resolve the username the client typed at /login into the actual
 * Supabase auth email. Accepts:
 *   - A real email — used as-is.
 *   - A phone number (any format) — mapped to `<digits>@seeya.app`.
 *
 * Returns null if the input doesn't look like either.
 */
export function resolveLoginEmail(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return null;

  if (trimmed.includes("@")) {
    return trimmed.toLowerCase();
  }

  const digits = normalizePhone(trimmed);
  if (digits.length < 7) return null;
  return `${digits}@${SEEYA_INTERNAL_DOMAIN}`;
}
